[project]
name = "nanimono-honnyaku-asset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pip>=25.2",
    "spacy>=3.8.7",
    "urllib3==1.26.15",
]
